### PR TITLE
Fix react native bindings

### PR DESCRIPTION
**Pull request by medson10**

### CODE REVIEW

**Review by fakenickels — COMMENTED** [review]
These props are not forwarded by Paper to RN TextInput?

**Comment by medson10** [comment]
The props which I removed yes, but you said it has a way to use the rn bindings without declare like I was doing before.

**Comment by medson10** [comment]
There is not ?

**Comment by fakenickels** [comment]
in this case there isn't indeed

**Review by fakenickels — APPROVED** [review]

**Pull request merged**
