### PR TITLE
Rename paper to surface and makes react-native-paper peerDependency.

### PR DESCRIPTION
**Pull request by Trancever**

### CODE REVIEW

**Review by medson10 — APPROVED** [review]

**Comment by medson10** [comment]
The test is failing probably because some difference between the versions of bs-platform, try to upgrade this please.

**Comment by Trancever** [comment]
Closes #25

**Comment by Trancever** [comment]
@medson10 Do you know why this first check "WIP" does not run?

**Comment by medson10** [comment]
@Trancever no, should be getting this status of the title, hmm maybe need an admin approve

**Comment by Trancever** [comment]
@medson10 Can you ask someone with admin privileges to check this?

**Comment by medson10** [comment]
@Trancever I think need be an admin of callstackincubator, just asked review from @grabbou @knowbody

**Review by knowbody — APPROVED** [review]

**Pull request merged**
